CREATE DATABASE XAMARIN_ANDROID;
USE XAMARIN_ANDROID;

CREATE TABLE TB_USUARIO(
ID_US INT AUTO_INCREMENT PRIMARY KEY,
NOME_US VARCHAR(100),
EMAIL_US VARCHAR(100),
SENHA_US VARCHAR(20)
);

-- USUARIO  DE ADMINSTRAÇÃO
INSERT INTO TB_USUARIO(NOME_US, EMAIL_US, SENHA_US)
 VALUES("adm", "adm@admin.com", '123');

